spring:
#MQ配置信息
  activemq:
    broker-url: tcp://192.168.186.130:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false      # false = queue    true =  topic
#数据库连接池
  datasource:
    url: jdbc:mysql://192.168.186.130:3306/mq-transaction?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Zet5la6f08lnSuW9s8z2mEKnE4f+FSkWfnb868WZ1qW5adcLd9pnzUnUD/oBRNcYcVQFjbJwq9zobBgrBjYluw==
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMTokHNbC3Q9XLZaoJM/6cBAwkDAbeILUCLabSGR1D1a8omgnSEUzVhtSTFQSRNv+BrB4WIoRW4l4uA4WFAdR78CAwEAAQ==
    driverClassName: com.mysql.jdbc.Driver
    #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：1、监控统计用的filter:stat；2、日志用的filter:log4j；3、防御sql注入的filter:wall
    filters: config
    #最大连接池数量
    maxActive: 450
    #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 10
    #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    #最小连接池数量
    minIdle: 10
    #有两个含义：1、Destroy线程会检测连接的间隔时间；2、testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    timeBetweenEvictionRunsMillis: 120000
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
    validationQuery: SELECT * FROM baseconfig where id = 'imgfilerelativepath';
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    maxOpenPreparedStatements: 100
    #是否打开 removeAbandoned 功能
    removeAbandoned: true
    #300 秒，也就是 5 分钟
    removeAbandonedTimeout: 300
    #是否关闭 abanded 连接时输出错误日志
    logAbandoned: true
  redis:
    redis1:
      # redis1
      database: 0
      host: 192.168.186.130
      port: 6379
      password: 123456
    # redis2
    redis2:
      database: 1
      host: 192.168.186.130
      port: 6380
      password: 123456
    timeout: 30000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 300
        min-idle: 0
server:
  port: 8082
#zk配置项
zookeeper:
  zkAddress: 192.168.186.130:2181
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 队列名称
myqueue: boot-activemq-queue
